module: DMSSDK
author: American Red Cross
author_url: https://americanredcross.com/
github_url: https://github.com/americanredcross/dmssdk-ios-framework
github-file-prefix: https://github.com/americanredcross/dmssdk-ios-framework/tree/master
clean: true
exclude: [DMSSDK/Utilities.swift]
copyright: '© 2017 [American Red Cross](https://americanredcross.com).'
readme: README.md
